artifacts_root : artifacts

data_ingestion:
  root_dir                     : artifacts/data_ingestion
  source_url                   : https://github.com/AarizZafar/image_source/raw/main/poxVisionDataSet.zip
  local_data_file              : artifacts/data_ingestion/data.zip
  unzip_dir                    : artifacts/data_ingestion